/**
 * The typed RPC client — the only module that calls the server's functions.
 *
 * Layer §2 of docs/accounts-plan.md: screens never import `supabase`, they go through
 * `src/server/`. Everything the economy touches goes through the P3 functions rather than
 * the tables, because `player_state`, `answers` and `lesson_completions` have a select
 * policy and nothing else (§3 rule 3) — there is no other door.
 *
 * The row and argument shapes come from `database.types.ts`, generated by
 * `npm run gen:types`. The functions return `json`, so the generator can only type them
 * as `Json`; the readers at the bottom of this file are what turn that into the
 * camelCase shapes the app uses, and they throw rather than hand a `NaN` to the store.
 */

import { supabase } from '../auth/supabase';
import type { Json } from './database.types';
import type { Profile } from './profile';

/**
 * Every failure the RPCs raise by name, plus the two the client decides for itself.
 * `UNREACHABLE` is a dead network — supabase-js reports it with an empty code — and
 * `UNKNOWN` is anything the server said that we have no copy for.
 */
export type ServerErrorCode =
  | 'OUT_OF_HEARTS'
  | 'ALREADY_COMPLETED'
  | 'NO_ANSWERS'
  | 'UNKNOWN_QUESTION'
  | 'NOT_AUTHENTICATED'
  | 'NO_PLAYER_STATE'
  | 'NO_PROFILE'
  | 'INVALID_DISPLAY_NAME'
  | 'UNREACHABLE'
  | 'UNKNOWN';

/** A failed call, carrying the server's own name for what went wrong. */
export class ServerError extends Error {
  constructor(
    readonly code: ServerErrorCode,
    message: string,
  ) {
    super(message);
    this.name = 'ServerError';
  }
}

/**
 * The code of a failed call, or null for anything else that was thrown.
 *
 * Reads the property rather than testing `instanceof`, which is the one thing about a
 * subclassed `Error` that does not survive every transpile.
 */
export function serverErrorCode(error: unknown): ServerErrorCode | null {
  if (typeof error !== 'object' || error === null) return null;
  const code = (error as { code?: unknown }).code;
  return typeof code === 'string' && code in MESSAGES ? (code as ServerErrorCode) : null;
}

/** Copy for whatever was thrown, falling back to the generic message. */
export function serverErrorMessage(error: unknown): string {
  return MESSAGES[serverErrorCode(error) ?? 'UNKNOWN'];
}

/** Copy for each failure, in the app's voice. A raw Postgres string never reaches a user. */
const MESSAGES: Record<ServerErrorCode, string> = {
  OUT_OF_HEARTS: "You're out of hearts. The next one is on its way.",
  ALREADY_COMPLETED: "That lesson is already in the books.",
  NO_ANSWERS: 'That hand was never played, so there is nothing to save.',
  UNKNOWN_QUESTION: "That question isn't in the answer key. Try updating the app.",
  NOT_AUTHENTICATED: 'Your session has expired. Sign in again.',
  NO_PLAYER_STATE: "We couldn't find your seat at the table.",
  NO_PROFILE: "We couldn't find your profile.",
  INVALID_DISPLAY_NAME: 'A name needs between 2 and 24 characters.',
  UNREACHABLE: "We couldn't reach the table. Check your connection.",
  UNKNOWN: 'Something went wrong on our side.',
};

/** One column of the week chart. */
export type WeekDay = { day: string; answers: number };

/** What the app shows: hearts, streak, XP and the lessons behind them. */
export type PlayerState = {
  hearts: number;
  /** when the next heart lands, or null at full — there is no countdown to show */
  nextHeartAt: string | null;
  /** already resolved through `live_streak`, so a lapsed run reads as zero */
  streak: number;
  streakAtRisk: boolean;
  /** the caller's next local midnight */
  streakExpiresAt: string | null;
  longestStreak: number;
  /**
   * The run as stored: the same as `streak` while it is alive, and the number that
   * ended once it is not. Never zeroed on the server — a lapse is derived (§6).
   */
  storedStreak: number;
  /** the local day the run was last extended, or null for a player who never had one */
  streakDay: string | null;
  xp: number;
  /** correct over total, 0–1 */
  accuracy: number;
  completedLessons: string[];
  /** answers per local day, seven days ending today, oldest first */
  week: WeekDay[];
  /** lessons finished on the local day, against the goal of three */
  lessonsToday: number;
  /** completions per chapter id — the server's own count of what the Path derives */
  chapters: Record<string, number>;
  /** games recorded; zero for everyone until P19 writes them */
  games: number;
  /**
   * The server's clock when it answered. Countdowns are measured against this and the
   * offset it implies, never against the device clock (§3 rule 8).
   */
  serverNow: string;
};

/** What `submit_answer` decided. Correctness is the server's to say, not the client's. */
export type AnswerOutcome = {
  correct: boolean;
  hearts: number;
  nextHeartAt: string | null;
};

/**
 * Minutes east of UTC — the sign `make_interval(mins => tz_offset_min)` expects, and the
 * opposite of what `Date#getTimezoneOffset` returns. The client sends an instant and this
 * offset and never a date (§6); the server derives the local day itself.
 */
export function tzOffsetMin(at: Date = new Date()): number {
  return -at.getTimezoneOffset();
}

/** Everything the app shows, with the caller's hearts settled as of now. */
export async function getState(): Promise<PlayerState> {
  const { data, error } = await supabase.rpc('get_state');
  if (error) throw failure(error);
  return toPlayerState(data);
}

/**
 * One answer. The client sends what was picked, never whether it was right — the answer
 * key in `content_questions` decides (§3 rule 5).
 *
 * `clientEventId` is what makes a replayed outbox entry a no-op rather than a second
 * spent heart (§3 rule 9), so it must be generated once per answer and reused on retry.
 */
export async function submitAnswer(answer: {
  lessonId: string;
  questionIndex: number;
  chosenOptionId: string;
  clientEventId: string;
  occurredAt?: Date;
  tzOffsetMin?: number;
}): Promise<AnswerOutcome> {
  const occurredAt = answer.occurredAt ?? new Date();
  const { data, error } = await supabase.rpc('submit_answer', {
    p_lesson_id: answer.lessonId,
    p_question_index: answer.questionIndex,
    p_chosen_option_id: answer.chosenOptionId,
    p_occurred_at: occurredAt.toISOString(),
    p_tz_offset_min: answer.tzOffsetMin ?? tzOffsetMin(occurredAt),
    p_client_event_id: answer.clientEventId,
  });
  if (error) throw failure(error);

  const row = record(data);
  return {
    correct: bool(row, 'is_correct'),
    hearts: num(row, 'hearts'),
    nextHeartAt: nullableStr(row, 'next_heart_at'),
  };
}

/** Finishes a lesson and applies the streak rule, returning the state that results. */
export async function completeLesson(completion: {
  lessonId: string;
  chapterId: string;
  clientEventId: string;
  occurredAt?: Date;
  tzOffsetMin?: number;
}): Promise<PlayerState> {
  const occurredAt = completion.occurredAt ?? new Date();
  const { data, error } = await supabase.rpc('complete_lesson', {
    p_lesson_id: completion.lessonId,
    p_chapter_id: completion.chapterId,
    p_occurred_at: occurredAt.toISOString(),
    p_tz_offset_min: completion.tzOffsetMin ?? tzOffsetMin(occurredAt),
    p_client_event_id: completion.clientEventId,
  });
  if (error) throw failure(error);
  return toPlayerState(data);
}

/**
 * A null argument leaves that field alone — the function's own contract, so the name can
 * be changed without resending the avatar and the other way round.
 *
 * Writes go through the function, never through `profiles`: RLS grants rows rather than
 * columns, so this is the one door that cannot rewrite `created_at` or `user_id`.
 */
export async function setProfile(
  displayName: string | null,
  avatarId: string | null,
): Promise<Profile> {
  const { data, error } = await supabase.rpc('set_profile', {
    // the generated Args type is not null-aware; the function's contract is
    p_display_name: displayName as string,
    p_avatar_id: avatarId as string,
  });
  if (error) throw failure(error);

  const row = record(data);
  return {
    displayName: nullableStr(row, 'display_name'),
    avatarId: nullableStr(row, 'avatar_id'),
  };
}

/** Everything hangs off `auth.users` by cascade, so the one delete takes the lot. */
export async function deleteAccount(): Promise<void> {
  const { error } = await supabase.rpc('delete_account');
  if (error) throw failure(error);
}

/**
 * Everything the account holds: profile, hearts and streak, every answer and completion,
 * the chip case and the games. The shape is `get_export()`'s, and it is deliberately left
 * as it came.
 *
 * The readers below exist because a screen cannot render a `Json`; this is not for a
 * screen. It is written to a file and handed to the player, so turning it into camelCase
 * on the way would only mean handing them a document that no longer matches the one the
 * server can be asked for again. `record` is the whole check — an answer that is not an
 * object is not a document, and must not reach a file as the word `null`.
 */
export async function getExport(): Promise<AccountExport> {
  const { data, error } = await supabase.rpc('get_export');
  if (error) throw failure(error);
  return record(data);
}

/** The export document, read as a whole rather than field by field. */
export type AccountExport = Row;

// ──────────────────────────────────────────────────────────────────── the wire

/** A PostgREST error, turned into one of ours. Only the mapping produces a message. */
function failure(error: { message: string; code?: string }): ServerError {
  // the functions raise by name, so the message *is* the code
  const raised = error.message.trim();
  if (raised in MESSAGES) {
    const code = raised as ServerErrorCode;
    return new ServerError(code, MESSAGES[code]);
  }
  // supabase-js reports a dead network with an empty code and a fetch message
  const code: ServerErrorCode = error.code ? 'UNKNOWN' : 'UNREACHABLE';
  return new ServerError(code, MESSAGES[code]);
}

type Row = { [key: string]: Json | undefined };

function record(value: Json): Row {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new ServerError('UNKNOWN', MESSAGES.UNKNOWN);
  }
  return value;
}

function wrong(field: string): ServerError {
  return new ServerError('UNKNOWN', `The server sent a ${field} we can't read.`);
}

function num(row: Row, field: string): number {
  const value = row[field];
  if (typeof value !== 'number' || !Number.isFinite(value)) throw wrong(field);
  return value;
}

function bool(row: Row, field: string): boolean {
  const value = row[field];
  if (typeof value !== 'boolean') throw wrong(field);
  return value;
}

function str(row: Row, field: string): string {
  const value = row[field];
  if (typeof value !== 'string') throw wrong(field);
  return value;
}

function nullableStr(row: Row, field: string): string | null {
  const value = row[field];
  if (value === null || value === undefined) return null;
  if (typeof value !== 'string') throw wrong(field);
  return value;
}

function strings(row: Row, field: string): string[] {
  const value = row[field];
  if (!Array.isArray(value) || value.some((id) => typeof id !== 'string')) throw wrong(field);
  return value as string[];
}

/** The week, one row per day, validated so a malformed chart cannot reach the screen. */
function week(row: Row, field: string): WeekDay[] {
  const value = row[field];
  if (!Array.isArray(value)) throw wrong(field);

  return value.map((entry) => {
    const day = record(entry as Json);
    return { day: str(day, 'day'), answers: num(day, 'answers') };
  });
}

/** `{ "hand-ranks": 8 }` — completions per chapter, or nothing at all. */
function counts(row: Row, field: string): Record<string, number> {
  const value = row[field];
  if (typeof value !== 'object' || value === null || Array.isArray(value)) throw wrong(field);

  const out: Record<string, number> = {};
  for (const [chapter, finished] of Object.entries(value)) {
    if (typeof finished !== 'number') throw wrong(field);
    out[chapter] = finished;
  }
  return out;
}

/** `get_state` and `complete_lesson` both answer with this shape. */
export function toPlayerState(data: Json): PlayerState {
  const row = record(data);
  return {
    hearts: num(row, 'hearts'),
    nextHeartAt: nullableStr(row, 'next_heart_at'),
    streak: num(row, 'streak_count'),
    streakAtRisk: bool(row, 'streak_at_risk'),
    streakExpiresAt: nullableStr(row, 'streak_expires_at'),
    longestStreak: num(row, 'longest_streak'),
    storedStreak: num(row, 'stored_streak_count'),
    streakDay: nullableStr(row, 'streak_day'),
    xp: num(row, 'xp'),
    accuracy: num(row, 'accuracy'),
    completedLessons: strings(row, 'completed_lesson_ids'),
    week: week(row, 'week'),
    lessonsToday: num(row, 'lessons_today'),
    chapters: counts(row, 'chapters'),
    games: num(row, 'games'),
    serverNow: str(row, 'server_now'),
  };
}
